name: Release @panva/hpke-noble

permissions: {}

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      actions: read
      contents: write
      discussions: write
      id-token: write
    uses: panva/.github/.github/workflows/npm-release.yml@bd045b0d7d15f7827910cdedd3e7f0570bc5bf58
    with:
      github_release: false
      maintenance_branch: false
      manifest_directory: ./examples/noble-suite
      package_directory: ./examples/noble-suite
      artifact_check_command: node tools/test-dist.js "$PACKAGE_TARBALL" examples/noble-suite
      prepare_command: npm clean-install && node --run build
      tagged_release: false
